name: Build/Test/Cover Project

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: "3.17.x"
      - name: checkout repo
        uses: actions/checkout@v2
      - name: build
        run: mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make && cd ..
      - name: tests
        run: ./build/runTests
      - name: coverage
        run: gcovr -r . --exclude "build/" --exclude "tests/"
