name: Build/Test/Cover Project [Linux]

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: "3.17.x"
      - name: checkout repo
        uses: actions/checkout@v2
      - run: mkdir -p build && cd build
      - name: build
        run: cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
      - name: makefile
        run: cd build && make
      - name: tests
        run: ./build/runTests
      - name: install gcovr
        run: sudo apt-get install -y gcovr
      - name: launch coverage
        run: gcovr -r . --exclude "build/" --exclude "tests/"