name: Build and Deploy Doxygen Documentation

on:
  push:
    branches:
      - main
      - develop

jobs:
  Doxygen:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: create doc
        uses: mattnotmitt/doxygen-action@v1.9.5
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doxydoc/html
